### PR TITLE
Update for qb-target and polyzone

### PR DESCRIPTION
**Pull request by deandum**
To enable qb-target for apartments, change Config.UseTarget to true in config.lua.

See discord for additional notes on this PR.

This PR should not be merged until qb-core:DrawText is merged on master.

### CODE REVIEW

**Comment by FjamZoo** [comment]
The 2 issues I found so far is the following

1. The target has no icons which can be found here https://fontawesome.com/search?m=free&s=solid%2Cbrands

2. We should avoid using table.insert where possible as table[#table+1] is more optimized as a whole. 

Otherwise seems to be working 👍

**Comment by deandum** [comment]
> The 2 issues I found so far is the following
> 
> 1. The target has no icons which can be found here https://fontawesome.com/search?m=free&s=solid%2Cbrands
> 2. We should avoid using table.insert where possible as table[#table+1] is more optimized as a whole.
> 
> Otherwise seems to be working 👍

We talked about 1. in discord. 
I pushed the changes requested for 2.

**Comment by Howsn** [comment]
After buying the house I will only get the view house option, it dosent update that you bought the house it looks like.

**Comment by Howsn** [comment]
Thanks for this awsome update! :D

I have a few problem, dont know if its just me?

1. After you create a house as realestate you only get the option "view house", you cant enter it and invite players inside to have a look.

2. Also after selling a house we can only get the "view house" to show, I need to ensure the script for it to show "enter".

**Comment by deandum** [comment]
> Thanks for this awsome update! :D
> 
> I have a few problem, dont know if its just me?
> 
> 1. After you create a house as realestate you only get the option "view house", you cant enter it and invite players inside to have a look.
> 2. Also after selling a house we can only get the "view house" to show, I need to ensure the script for it to show "enter".

I will take a look. Thanks for the feedback.

**Comment by deandum** [comment]
> > Thanks for this awsome update! :D
> > I have a few problem, dont know if its just me?
> > 
> > 1. After you create a house as realestate you only get the option "view house", you cant enter it and invite players inside to have a look.
> > 2. Also after selling a house we can only get the "view house" to show, I need to ensure the script for it to show "enter".
> 
> I will take a look. Thanks for the feedback.

Should be fixed now

**Comment by Howsn** [comment]
> 

I change it to this and no more errors. :)

QBCore.Functions.CreateCallback('qb-houses:server:isOwned', function(source, cb, house)
    local src = source
    local Player = QBCore.Functions.GetPlayer(src)
    if Player then
        if Player.PlayerData.job.name == "realestate" then
            cb(true)
        elseif houseowneridentifier[house] and houseownercid[house] then
            cb(true)
        else
            cb(false)
        end
    end
end)

**Comment by Howsn** [comment]
I have tested alot now and found a few more bugs.

1. When entering a house I dont always get to trigger the eye when leaving the house
2. When standing at "stash", "clothing" or "logout" location my F8 get spammed wih this.
https://gyazo.com/74725901358e73439b488a5e4e193aec

**Comment by deandum** [comment]
> I have tested alot now and found a few more bugs.
> 
> 1. When entering a house I dont always get to trigger the eye (like the polyzone is not there) and i'm stuck inside the house.
> 2. When standing at "stash", "clothing" or "logout" location my F8 get spammed wih this.
>    https://gyazo.com/74725901358e73439b488a5e4e193aec

Are you actually testing this version of the script or have you adapted your own to use this? Because I am not able to reproduce any of the issues you are talking about. Either test with this exact version or write a detailed step-by-step reproduction guide.

**Comment by DannysRP** [comment]
Something small here. When placing locations (stash/outfits/logout) you have to leave the house and go back inside for it to show up

**Comment by deandum** [comment]
> Something small here. When placing locations (stash/outfits/logout) you have to leave the house and go back inside for it to show up

I will fix this, thanks!

**Comment by DannysRP** [comment]
Sometimes target options do not show up for the entrance or exit of the home. We've had quite a few instances where one person can see the exit target options but another person in the house at the same time cannot. Same for target options at the entrance for both home owners/real estate agents.

**Comment by deandum** [comment]
> Sometimes target options do not show up for the entrance or exit of the home. We've had quite a few instances where one person can see the exit target options but another person in the house at the same time cannot. Same for target options at the entrance for both home owners/real estate agents.

Target only works when it overlaps with an entity... like a door, a piece of furniture, the ground... anything that is considered an entity. So if you are adding a house in the middle of nowhere and there is no entity around to target, then it won't show. The same goes for the exit target. If you are using different interiors than the ones we provide, you will need to update the code to create the target on the right coordinates and make sure that it overlaps an entity.

**Comment by DannysRP** [comment]
Yes I do understand that but the target shows up and some times it doesn't. That's the issue we run into. (using only K4mbi shells as well

**Comment by deandum** [comment]
> 

So are you setting the offsets for each interior so that the target coords are on top of an entity? Honestly, you might be better off just creating the exit location yourself as it works with the stash, outfits, and logout. I was actually going to change that, but no time, unfortunately.

**Comment by DannysRP** [comment]
Yeah the stash/outfits/logout seem to work only issues is with entrances and exits. We usually place entrances right on the door of houses

**Comment by deandum** [comment]
> Yeah the stash/outfits/logout seem to work only issues is with entrances and exits. We usually place entrances right on the door of houses

Yeah, I would honestly not use target at all for this resource. Just set `UseTarget` to false in the config. It's mostly added as an example on how to implement it... it's not really supposed to work with all the possible houses and interiors without code changes.

**Comment by Howsn** [comment]
I have also tested this now hand have some problem with qb-target. For me I can see the house but for the realestate he cant. This looks to go back and fourth, somethimes it works and somethimes it dosent. And its only for enter/exit

**Comment by deandum** [comment]
> I have also tested this now hand have some problem with qb-target. For me I can see the house but for the realestate he cant, I can ensure the script and he can see it again. This looks to go back and fourth, somethimes it works and somethimes it dosent. And its only for enter/exit

Honestly, I think I will take away qb-target for this. I think PZ + keypress is a good starting point. Ideally, PZ and radial menu should take care of all the issues. qb-target is kind of hard to use with houses since the coordinates are not fixed by scripts.

**Comment by Howsn** [comment]
> > I have also tested this now hand have some problem with qb-target. For me I can see the house but for the realestate he cant, I can ensure the script and he can see it again. This looks to go back and fourth, somethimes it works and somethimes it dosent. And its only for enter/exit
> 
> Honestly, I think I will take away qb-target for this. I think PZ + keypress is a good starting point. Ideally, PZ and radial menu should take care of all the issues. qb-target is kind of hard to use with houses since the coordinates are not fixed by scripts.

Yeah its wierd, so sad to see this go 😭 but I understand that it is hard. But if you go back to keypress I have one request, or a way I can fix this myself. But when you press "E" to open the housing menu, is it possible to get the mouse to work right away? So you dont have to use the "toggle" Key to use the menu.

**Comment by deandum** [comment]
> > > I have also tested this now hand have some problem with qb-target. For me I can see the house but for the realestate he cant, I can ensure the script and he can see it again. This looks to go back and fourth, somethimes it works and somethimes it dosent. And its only for enter/exit
> > 
> > 
> > Honestly, I think I will take away qb-target for this. I think PZ + keypress is a good starting point. Ideally, PZ and radial menu should take care of all the issues. qb-target is kind of hard to use with houses since the coordinates are not fixed by scripts.
> 
> Yeah its wierd, so sad to see this go 😭 but I understand that it is hard. But if you go back to keypress I have one request, or a way I can fix this myself. But when you press "E" to open the housing menu, is it possible to get the mouse to work right away? So you dont have to use the "toggle" Key to use the menu.

Yeah, will do.

**Review by ANZGamingNetworks — APPROVED** [review]

**Pull request merged**
