### PR TITLE
Update for GetHouseStreetCount()

### PR DESCRIPTION
**Pull request by Borreke0**
This solves a problem for duplication in addresses.
When wrong/unbought houses get deleted the old function just 'counts' the amount of addresses from that street and generates a number on that value.
E.g.:
Before deletion you have like
- Xx st1
- Xx st2
- Xx st3
You delete Xx st2 and the old functions generates "Xx st3" as new address (but this already exists so a user gets conflicts with keys etc)
New function will search for "Xx st3" and will make "Xx st4" :-)

This function will select the full address last submitted from that street and will increase the last known housenumber by 1.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? Yes
- Does your code fit the style guidelines? Yes
- Does your PR fit the contribution guidelines? Yes

### CODE REVIEW

**Comment by nzkfc** [comment]
So I pulled a fresh qb-core to try some things out on this issue, here were my steps to recreate:

1. Create a bunch of houses in the same street, say round 6 or 8.
2. Go into the DB and delete houses between the first and the last. Say 2,3,4,5
3. Create a new house, the number will either set as 2,3,4,5 or it will do 1 or 6 duplicating the address
(Also obvisouly it would sequentially go up and duplicate anyways as it has no check for address number duplicates.

**Comment by nzkfc** [comment]
> If I'm looking at this correctly... the house number may be scuffed when a string contains more than one space. I wrote this function I've been testing for a few weeks. No issues so far. Particularly, I had issues with addresses in ranges like offices on Runway1 (LSIA). So I had to write the function below to do something very similar to what you are doing here.
> 
> ```lua
> local function GetHouseStreetCount(street)
>     local count = 0
>     local query = '%' .. street .. '%'
>     local result = MySQL.Sync.fetchSingle('SELECT * FROM houselocations WHERE name LIKE ? ORDER BY LENGTH(`name`) desc, `name` DESC', {query})
>     if result then
>         local houseAddress = result.name
>         count = tonumber(string.match(houseAddress, '%d[%d.,]*'))
>     end
>     return (count + 1)
> end
> ```

How has this been going for you?

**Comment by jnccloud** [comment]
> > If I'm looking at this correctly... the house number may be scuffed when a string contains more than one space. I wrote this function I've been testing for a few weeks. No issues so far. Particularly, I had issues with addresses in ranges like offices on Runway1 (LSIA). So I had to write the function below to do something very similar to what you are doing here.
> > ```lua
> > local function GetHouseStreetCount(street)
> >     local count = 0
> >     local query = '%' .. street .. '%'
> >     local result = MySQL.Sync.fetchSingle('SELECT * FROM houselocations WHERE name LIKE ? ORDER BY LENGTH(`name`) desc, `name` DESC', {query})
> >     if result then
> >         local houseAddress = result.name
> >         count = tonumber(string.match(houseAddress, '%d[%d.,]*'))
> >     end
> >     return (count + 1)
> > end
> > ```
> 
> How has this been going for you?

The function I posted, I've been using for months. I have not tested this PR itself..

**Comment by nzkfc** [comment]
Ok I will implement this and see also, fingers crossed.

**Comment by nzkfc** [comment]
So I implemented @jnccloud function and did:

1. Went to street that had 2 houses on it already.
2. Added 6 houses down the street
3. Refreshed DB and now has 8 houses
4. Delete house 3,4,5
5. Check those spots, no longer a house there for sale
6. Go back to spot 3, 4, 5 and create the houses again
7. Houses 9, 10 and 11 get created and all seems to work well.

Seems that this is a good result.

**Comment by nzkfc** [comment]
17 days later and this is still working great for us.

**Comment by jnccloud** [comment]
> 17 days later and this is still working great for us.

Are you using the function from my comment or the one in this PR?

**Comment by nzkfc** [comment]
> > 17 days later and this is still working great for us.
> 
> Are you using the function from my comment or the one in this PR?

Ahh sorry yeah yours

**Pull request closed without merging**
