### PR TITLE
event show all blip house for player use by admin

### PR DESCRIPTION
**Pull request by evanillaa**
You can now view all homes through the administrator
You can use this event for that

**Describe Pull request**

event show all blip house for player use by admin

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Review by jnccloud — CHANGES_REQUESTED** [review]
Why is this registering a server event in client/main.lua?

**Comment by BerkieBb** [comment]
And why is the table global?

**Comment by evanillaa** [comment]
now add local

**Comment by BerkieBb** [comment]
Did you test this? Because at how this looks nowz it will not do anything at all

**Pull request closed without merging**
